export const DELETE_ITEM = "DELETE_ITEM";
export const ADD_ITEM_FAVORITE = "ADD_ITEM_FAVORITE";
export const GET_ITEM_LOADING = "GET_ITEM_LOADING";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_ERROR = "GET_ITEM_ERROR";
